# Writes OUT (git_info.h) with the source tree's commit, branch and dirty flag; run on every build (cmake -P).
# The file is only rewritten when the values change, so unchanged builds don't recompile.
function(git_out var)
    execute_process(COMMAND git ${ARGN} WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE out RESULT_VARIABLE rc
            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT rc EQUAL 0)
        set(out "unknown")
    endif()
    set(${var} "${out}" PARENT_SCOPE)
endfunction()

git_out(GIT_COMMIT rev-parse HEAD)
git_out(GIT_BRANCH branch --show-current)
if(GIT_BRANCH STREQUAL "")
    set(GIT_BRANCH "detached")
endif()
git_out(GIT_STATUS status --porcelain --untracked-files=no) # tracked changes only
if(GIT_COMMIT STREQUAL "unknown")
    set(GIT_DIRTY "false") # no repo
elseif(GIT_STATUS STREQUAL "")
    set(GIT_DIRTY "false")
else()
    set(GIT_DIRTY "true")
endif()

file(CONFIGURE OUTPUT "${OUT}" CONTENT [[#pragma once
// generated by cmake/git_info.cmake at build time
#define NANOCHAT_GIT_COMMIT "@GIT_COMMIT@"
#define NANOCHAT_GIT_BRANCH "@GIT_BRANCH@"
#define NANOCHAT_GIT_DIRTY @GIT_DIRTY@
]] @ONLY)
