# Writes OUT (git_info.h) with the source tree's branch; run on every build (cmake -P).
# The file is only rewritten when the branch changes, so unchanged builds don't recompile.
execute_process(COMMAND git branch --show-current WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE GIT_BRANCH
        RESULT_VARIABLE rc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT rc EQUAL 0)
    set(GIT_BRANCH "unknown") # no repo
elseif(GIT_BRANCH STREQUAL "")
    set(GIT_BRANCH "detached")
endif()

file(CONFIGURE OUTPUT "${OUT}" CONTENT [[#pragma once
// generated by cmake/git_info.cmake at build time
#define NANOCHAT_GIT_BRANCH "@GIT_BRANCH@"
]] @ONLY)
